import type { SupplierFeedProduct } from "./types";

/**
 * Static feed for the demo wholesale supplier ("demo-wholesale-v1").
 * Items DW-1001…DW-1008 correspond to products already linked in the store
 * catalog; DW-2001…DW-2006 exist only in the supplier feed and can be
 * imported via Admin → Suppliers → Sync / Import.
 */
export const DEMO_CATALOG: SupplierFeedProduct[] = [
  {
    externalId: "DW-1001",
    name: "Wireless Earbuds Pro (Wholesale)",
    description: "ANC wireless earbuds, 36h battery with case, IPX5. Wholesale unit.",
    images: ["/products/wireless-earbuds-1.jpg", "/products/wireless-earbuds-2.jpg"],
    price: 1650,
    stock: 140,
    sku: "DW-EAR-1001",
    category: "Electronics",
    variants: [{ group: "Color", options: ["Black", "White"] }],
    specs: [
      { group: "Audio", key: "Driver", value: "13mm dynamic" },
      { group: "Audio", key: "Battery", value: "36h with case" },
    ],
  },
  {
    externalId: "DW-1002",
    name: "Smart Watch Series X (Wholesale)",
    description: "1.9 inch AMOLED smartwatch with health tracking.",
    images: ["/products/smart-watch-1.jpg", "/products/smart-watch-2.jpg"],
    price: 2100,
    stock: 85,
    sku: "DW-WAT-1002",
    category: "Electronics",
    specs: [
      { group: "Display", key: "Screen", value: "1.9 inch AMOLED" },
      { group: "Battery", key: "Capacity", value: "320mAh" },
    ],
  },
  {
    externalId: "DW-1003",
    name: "Portable Bluetooth Speaker (Wholesale)",
    description: "20W speaker with 12h playtime, IPX6.",
    images: ["/products/bluetooth-speaker-1.jpg", "/products/bluetooth-speaker-2.jpg"],
    price: 1350,
    stock: 96,
    sku: "DW-SPK-1003",
    category: "Electronics",
  },
  {
    externalId: "DW-1004",
    name: "Power Bank 20000mAh (Wholesale)",
    description: "22.5W fast charge power bank, dual USB + Type-C.",
    images: ["/products/power-bank-2.jpg"],
    price: 1180,
    stock: 64,
    sku: "DW-PWB-1004",
    category: "Electronics",
  },
  {
    externalId: "DW-1005",
    name: "Mechanical Keyboard RGB (Wholesale)",
    description: "Hot-swappable red switches, RGB, double-shot keycaps.",
    images: ["/products/mechanical-keyboard-1.jpg", "/products/mechanical-keyboard-2.jpg"],
    price: 2250,
    stock: 42,
    sku: "DW-KBD-1005",
    category: "Electronics",
  },
  {
    externalId: "DW-1006",
    name: "Wireless Silent Mouse (Wholesale)",
    description: "2.4GHz silent click mouse, 18-month battery.",
    images: ["/products/wireless-mouse-1.jpg"],
    price: 520,
    stock: 210,
    sku: "DW-MOU-1006",
    category: "Electronics",
  },
  {
    externalId: "DW-1007",
    name: "Eco Yoga Mat 8mm (Wholesale)",
    description: "Non-slip TPE yoga mat with carry strap.",
    images: ["/products/yoga-mat-1.jpg", "/products/yoga-mat-2.jpg"],
    price: 640,
    stock: 58,
    sku: "DW-YOG-1007",
    category: "Sports & Outdoors",
  },
  {
    externalId: "DW-1008",
    name: "City Laptop Backpack 25L (Wholesale)",
    description: "Water-resistant backpack with padded 15.6 inch laptop bay.",
    images: ["/products/laptop-backpack-1.jpg", "/products/laptop-backpack-2.jpg"],
    price: 980,
    stock: 73,
    sku: "DW-BAG-1008",
    category: "Bags & Accessories",
  },
  {
    externalId: "DW-2001",
    name: "Over-Ear Wireless Headphones ANC",
    description: "Active noise-cancelling over-ear headphones with 40h playtime and USB-C fast charge.",
    images: ["/products/wireless-earbuds-2.jpg", "/products/wireless-earbuds-3.jpg"],
    price: 2450,
    stock: 35,
    sku: "DW-HDP-2001",
    category: "Electronics",
    variants: [{ group: "Color", options: ["Black", "Beige"] }],
    specs: [
      { group: "Audio", key: "ANC", value: "Hybrid, up to 35dB" },
      { group: "Audio", key: "Battery", value: "40 hours" },
      { group: "Connectivity", key: "Bluetooth", value: "5.3" },
    ],
  },
  {
    externalId: "DW-2002",
    name: "15W Fast Wireless Charging Pad",
    description: "Qi-certified charging pad with silicone grip surface and LED indicator.",
    images: ["/products/fast-charger-2.jpg", "/products/fast-charger-3.jpg"],
    price: 890,
    stock: 120,
    sku: "DW-WCG-2002",
    category: "Electronics",
  },
  {
    externalId: "DW-2003",
    name: "Braided Type-C Cable 2m",
    description: "60W braided USB-C cable with reinforced connectors.",
    images: ["/products/fast-charger-4.jpg"],
    price: 350,
    stock: 300,
    sku: "DW-CBL-2003",
    category: "Electronics",
  },
  {
    externalId: "DW-2004",
    name: "Insulated Travel Tumbler 450ml",
    description: "Double-wall vacuum tumbler that keeps drinks hot for 6 hours.",
    images: ["/products/ceramic-mugs-3.jpg", "/products/ceramic-mugs-4.jpg"],
    price: 750,
    stock: 88,
    sku: "DW-TUM-2004",
    category: "Home & Living",
  },
  {
    externalId: "DW-2005",
    name: "Memory Foam Lumbar Cushion",
    description: "Ergonomic lumbar support cushion with breathable mesh cover.",
    images: ["/products/throw-pillows-3.jpg", "/products/throw-pillows-4.jpg"],
    price: 1200,
    stock: 45,
    sku: "DW-LUM-2005",
    category: "Home & Living",
  },
  {
    externalId: "DW-2006",
    name: "HD Dash Cam Pro",
    description: "1080p dash camera with night vision and loop recording.",
    images: ["/products/car-phone-mount-2.jpg"],
    price: 3200,
    stock: 26,
    sku: "DW-CAM-2006",
    category: "Electronics",
  },
];
